export const containers = [
  {
    type: 'grid',
    icon: 'grid',
    category: 'container',
    cols: [
      {
        type: 'grid-col',
        icon: 'grid-col',
        category: 'container',
        options: {
          name: 'gridCol1',
          span: 12,
          offset: 0,
          push: 0,
          pull: 0,
          responsive: '',
          md: 12,
          sm: 12,
          xs: 12,
          customClass: '',
        },
        widgetList: [],
        collapsed: false,
      },
      {
        type: 'grid-col',
        icon: 'grid-col',
        category: 'container',
        options: {
          name: 'gridCol2',
          span: 12,
          offset: 0,
          push: 0,
          pull: 0,
          responsive: '',
          md: 12,
          sm: 12,
          xs: 12,
          customClass: '',
        },
        widgetList: [],
        collapsed: false,
      },
    ],
    options: {
      name: 'grid1',
      hidden: false,
      customClass: '',
      responsive: false,
      colHeight: '',
      gutter: 0,
    },
    collapsed: false,
    internal: true,
  },
  {
    type: 'table',
    icon: 'table',
    category: 'container',
    options: {
      name: 'table1',
      hidden: false,
      customClass: '',
      rows: [
        {
          cols: [
            {
              options: {
                name: 'cell-1',
                colspan: 1,
                rowspan: 1,
                width: '',
                height: '',
              },
              merged: false,
              widgetList: [],
            },
          ],
        },
      ],
    },
    internal: true,
  },
  {
    type: 'tab',
    icon: 'tab',
    category: 'container',
    options: {
      name: 'tab1',
      hidden: false,
      customClass: '',
      tabType: 'border-card',
      tabPosition: 'top',
      defineTabs: [
        { name: 'tabPane1', label: 'Tab 1' },
        { name: 'tabPane2', label: 'Tab 2' },
      ],
    },
    tabs: [
      {
        options: {
          name: 'tabPane1',
          label: 'Tab 1',
          active: true,
        },
        widgetList: [],
      },
      {
        options: {
          name: 'tabPane2',
          label: 'Tab 2',
          active: false,
        },
        widgetList: [],
      },
    ],
    internal: true,
  },
  {
    type: 'sub-form',
    icon: 'sub-form',
    category: 'container',
    formItemFlag: true,
    options: {
      name: 'subForm1',
      label: '子表单',
      hidden: false,
      customClass: '',
      showBlankRow: true,
      showRowNumber: true,
      labelAlign: 'left',
    },
    widgetList: [],
    internal: true,
  },
]

export const basicFields = [
  {
    type: 'input',
    icon: 'text-field',
    formItemFlag: true,
    options: {
      name: '',
      label: '',
      labelAlign: '',
      type: 'text',
      defaultValue: '',
      placeholder: '',
      columnWidth: '200px',
      size: '',
      labelWidth: null,
      labelHidden: false,
      readonly: false,
      disabled: false,
      hidden: false,
      clearable: true,
      showPassword: false,
      required: false,
      validation: '',
      validationHint: '',
      customClass: '',
      labelIconClass: null,
      labelIconPosition: 'rear',
      labelTooltip: null,
      minLength: null,
      maxLength: null,
      showWordLimit: false,
      prefixIcon: '',
      suffixIcon: '',
      appendButton: false,
      appendButtonDisabled: false,
      buttonIcon: 'custom-search',
      onCreated: '',
      onMounted: '',
      onInput: '',
      onChange: '',
      onFocus: '',
      onBlur: '',
      onValidate: '',
    },
  },
  {
    type: 'textarea',
    icon: 'textarea',
    formItemFlag: true,
    options: {
      name: '',
      label: '',
      labelAlign: '',
      defaultValue: '',
      placeholder: '',
      columnWidth: '200px',
      size: '',
      labelWidth: null,
      labelHidden: false,
      readonly: false,
      disabled: false,
      hidden: false,
      required: false,
      validation: '',
      validationHint: '',
      customClass: '',
      maxLength: null,
      showWordLimit: false,
      rows: 4,
      cols: 30,
      onCreated: '',
      onMounted: '',
      onInput: '',
      onChange: '',
      onFocus: '',
      onBlur: '',
      onValidate: '',
    },
  },
  {
    type: 'number',
    icon: 'number-field',
    formItemFlag: true,
    options: {
      name: '',
      label: '',
      labelAlign: '',
      defaultValue: 0,
      placeholder: '',
      columnWidth: '200px',
      size: '',
      labelWidth: null,
      labelHidden: false,
      readonly: false,
      disabled: false,
      hidden: false,
      required: false,
      validation: '',
      validationHint: '',
      customClass: '',
      min: null,
      max: null,
      step: 1,
      precision: null,
      controls: true,
      controlsPosition: 'right',
      onCreated: '',
      onMounted: '',
      onInput: '',
      onChange: '',
      onFocus: '',
      onBlur: '',
      onValidate: '',
    },
  },
  {
    type: 'select',
    icon: 'select',
    formItemFlag: true,
    options: {
      name: '',
      label: '',
      labelAlign: '',
      defaultValue: '',
      placeholder: '',
      columnWidth: '200px',
      size: '',
      labelWidth: null,
      labelHidden: false,
      readonly: false,
      disabled: false,
      hidden: false,
      clearable: true,
      filterable: false,
      allowCreate: false,
      defaultFirstOption: false,
      multiple: false,
      multipleLimit: 0,
      required: false,
      validation: '',
      validationHint: '',
      customClass: '',
      options: [
        { label: 'Option 1', value: 1 },
        { label: 'Option 2', value: 2 },
      ],
      showLabel: false,
      optionItems: [],
      /* Data Source Options */
      dsEnabled: false,
      dsType: 'static',
      dsName: '',
      labelKey: 'label',
      valueKey: 'value',
      dsMethod: 'GET',
      dsDataPath: 'data',
      dsParams: [],
      dataTarget: '',
      linkageType: 'filter',
      targetValueKey: '',
      targetLabelKey: '',
      onCreated: '',
      onMounted: '',
      onChange: '',
      onFocus: '',
      onBlur: '',
      onValidate: '',
    },
  },
  {
    type: 'radio',
    icon: 'radio',
    formItemFlag: true,
    options: {
      name: '',
      label: '',
      labelAlign: '',
      defaultValue: '',
      columnWidth: '200px',
      size: '',
      labelWidth: null,
      labelHidden: false,
      disabled: false,
      hidden: false,
      required: false,
      validation: '',
      validationHint: '',
      customClass: '',
      options: [
        { label: 'Radio 1', value: 1 },
        { label: 'Radio 2', value: 2 },
      ],
      showLabel: false,
      optionItems: [],
      /* Data Source Options */
      dsEnabled: false,
      dsType: 'static',
      dsName: '',
      labelKey: 'label',
      valueKey: 'value',
      dsMethod: 'GET',
      dsDataPath: 'data',
      dsParams: [],
      dataTarget: '',
      linkageType: 'filter',
      targetValueKey: '',
      targetLabelKey: '',
      onCreated: '',
      onMounted: '',
      onChange: '',
      onValidate: '',
    },
  },
  {
    type: 'checkbox',
    icon: 'checkbox',
    formItemFlag: true,
    options: {
      name: '',
      label: '',
      labelAlign: '',
      defaultValue: [],
      columnWidth: '200px',
      size: '',
      labelWidth: null,
      labelHidden: false,
      disabled: false,
      hidden: false,
      required: false,
      validation: '',
      validationHint: '',
      customClass: '',
      min: null,
      max: null,
      options: [
        { label: 'Checkbox 1', value: 1 },
        { label: 'Checkbox 2', value: 2 },
      ],
      showLabel: false,
      optionItems: [],
      /* Data Source Options */
      dsEnabled: false,
      dsType: 'static',
      dsName: '',
      labelKey: 'label',
      valueKey: 'value',
      dsMethod: 'GET',
      dsDataPath: 'data',
      dsParams: [],
      dataTarget: '',
      linkageType: 'filter',
      targetValueKey: '',
      targetLabelKey: '',
      onCreated: '',
      onMounted: '',
      onChange: '',
      onValidate: '',
    },
  },
  {
    type: 'date',
    icon: 'date',
    formItemFlag: true,
    options: {
      name: '',
      label: '',
      labelAlign: '',
      defaultValue: '',
      placeholder: '',
      columnWidth: '200px',
      size: '',
      labelWidth: null,
      labelHidden: false,
      readonly: false,
      disabled: false,
      hidden: false,
      clearable: true,
      required: false,
      validation: '',
      validationHint: '',
      customClass: '',
      type: 'date',
      format: 'YYYY-MM-DD',
      timestamp: false,
      placeholderType: 'normal',
      startPlaceholder: '',
      endPlaceholder: '',
      onCreated: '',
      onMounted: '',
      onChange: '',
      onFocus: '',
      onBlur: '',
      onValidate: '',
    },
  },
  {
    type: 'time',
    icon: 'time',
    formItemFlag: true,
    options: {
      name: '',
      label: '',
      labelAlign: '',
      defaultValue: '',
      placeholder: '',
      columnWidth: '200px',
      size: '',
      labelWidth: null,
      labelHidden: false,
      readonly: false,
      disabled: false,
      hidden: false,
      clearable: true,
      required: false,
      validation: '',
      validationHint: '',
      customClass: '',
      type: 'time',
      format: 'HH:mm:ss',
      isRange: false,
      arrowControl: true,
      placeholderType: 'normal',
      startPlaceholder: '',
      endPlaceholder: '',
      onCreated: '',
      onMounted: '',
      onChange: '',
      onFocus: '',
      onBlur: '',
      onValidate: '',
    },
  },
  {
    type: 'switch',
    icon: 'switch',
    formItemFlag: true,
    options: {
      name: '',
      label: '',
      labelAlign: '',
      defaultValue: false,
      columnWidth: '200px',
      size: '',
      labelWidth: null,
      labelHidden: false,
      disabled: false,
      hidden: false,
      required: false,
      validation: '',
      validationHint: '',
      customClass: '',
      switchWidth: 40,
      activeText: '',
      inactiveText: '',
      activeColor: '',
      inactiveColor: '',
      onCreated: '',
      onMounted: '',
      onChange: '',
      onValidate: '',
    },
  },
  {
    type: 'slider',
    icon: 'slider',
    formItemFlag: true,
    options: {
      name: '',
      label: '',
      labelAlign: '',
      defaultValue: 0,
      columnWidth: '200px',
      size: '',
      labelWidth: null,
      labelHidden: false,
      disabled: false,
      hidden: false,
      required: false,
      validation: '',
      validationHint: '',
      customClass: '',
      min: 0,
      max: 100,
      step: 1,
      showInput: false,
      showStops: false,
      range: false,
      onCreated: '',
      onMounted: '',
      onChange: '',
      onValidate: '',
    },
  },
  {
    type: 'rate',
    icon: 'rate',
    formItemFlag: true,
    options: {
      name: '',
      label: '',
      labelAlign: '',
      defaultValue: 0,
      columnWidth: '200px',
      size: '',
      labelWidth: null,
      labelHidden: false,
      disabled: false,
      hidden: false,
      required: false,
      validation: '',
      validationHint: '',
      customClass: '',
      max: 5,
      allowHalf: false,
      showText: false,
      showScore: false,
      onCreated: '',
      onMounted: '',
      onChange: '',
      onValidate: '',
    },
  },
  {
    type: 'cascader',
    icon: 'cascader',
    formItemFlag: true,
    options: {
      name: '',
      label: '',
      labelAlign: '',
      defaultValue: [],
      placeholder: '',
      columnWidth: '200px',
      size: '',
      labelWidth: null,
      labelHidden: false,
      readonly: true,
      disabled: false,
      hidden: false,
      clearable: true,
      filterable: false,
      required: false,
      validation: '',
      validationHint: '',
      customClass: '',
      options: [],
      showLabel: false,
      optionItems: [],
      separator: '/',
      filter: false,
      collapseTags: false,
      /* Data Source Options */
      dsEnabled: false,
      dsType: 'static',
      dsName: '',
      labelKey: 'label',
      valueKey: 'value',
      dsMethod: 'GET',
      dsDataPath: 'data',
      dsParams: [],
      dataTarget: '',
      linkageType: 'filter',
      targetValueKey: '',
      targetLabelKey: '',
      onCreated: '',
      onMounted: '',
      onChange: '',
      onFocus: '',
      onBlur: '',
      onValidate: '',
    },
  },
]

export const advancedFields = [
  {
    type: 'color',
    icon: 'color',
    formItemFlag: true,
    options: {
      name: '',
      label: '',
      labelAlign: '',
      defaultValue: null,
      columnWidth: '200px',
      size: '',
      labelWidth: null,
      labelHidden: false,
      disabled: false,
      hidden: false,
      required: false,
      validation: '',
      validationHint: '',
      customClass: '',
      showAlpha: false,
      colorFormat: '',
      onCreated: '',
      onMounted: '',
      onChange: '',
      onValidate: '',
    },
  },
  {
    type: 'button',
    icon: 'button',
    category: 'field',
    options: {
      name: '',
      label: '',
      hidden: false,
      customClass: '',
      type: 'default',
      plain: false,
      round: false,
      circle: false,
      loading: false,
      disabled: false,
      icon: '',
      labelWidth: null,
      buttonType: '',
      onCreated: '',
      onMounted: '',
      onClick: '',
    },
  },
  {
    type: 'divider',
    icon: 'divider',
    category: 'field',
    options: {
      name: '',
      label: '',
      hidden: false,
      customClass: '',
      labelWidth: null,
      direction: 'horizontal',
      contentPosition: 'center',
      borderStyle: 'solid',
      color: '#DCDFE6',
      onCreated: '',
      onMounted: '',
    },
  },
  {
    type: 'static-text',
    icon: 'static-text',
    category: 'field',
    options: {
      name: '',
      label: '',
      hidden: false,
      customClass: '',
      labelWidth: null,
      textContent: 'Static Text',
      tag: 'span',
      onCreated: '',
      onMounted: '',
    },
  },
  {
    type: 'html-text',
    icon: 'html-text',
    category: 'field',
    options: {
      name: '',
      label: '',
      hidden: false,
      customClass: '',
      labelWidth: null,
      htmlContent: '<p>HTML Content</p>',
      onCreated: '',
      onMounted: '',
    },
  },
  {
    type: 'picture-upload',
    icon: 'picture-upload',
    formItemFlag: true,
    options: {
      name: '',
      label: '',
      labelAlign: '',
      defaultValue: [],
      columnWidth: '200px',
      size: '',
      labelWidth: null,
      labelHidden: false,
      disabled: false,
      hidden: false,
      required: false,
      validation: '',
      validationHint: '',
      customClass: '',
      accept: 'image/*',
      limit: 3,
      fileMaxSize: 5,
      showTip: false,
      action: '/upload',
      listType: 'picture-card',
      withCredentials: false,
      headers: {},
      data: {},
      onCreated: '',
      onMounted: '',
      onChange: '',
      onRemove: '',
      onPreview: '',
      onSuccess: '',
      onError: '',
      onValidate: '',
    },
  },
  {
    type: 'file-upload',
    icon: 'file-upload',
    formItemFlag: true,
    options: {
      name: '',
      label: '',
      labelAlign: '',
      defaultValue: [],
      columnWidth: '200px',
      size: '',
      labelWidth: null,
      labelHidden: false,
      disabled: false,
      hidden: false,
      required: false,
      validation: '',
      validationHint: '',
      customClass: '',
      accept: '',
      limit: 5,
      fileMaxSize: 10,
      showTip: false,
      action: '/upload',
      listType: 'text',
      withCredentials: false,
      headers: {},
      data: {},
      onCreated: '',
      onMounted: '',
      onChange: '',
      onRemove: '',
      onPreview: '',
      onSuccess: '',
      onError: '',
      onValidate: '',
    },
  },
  {
    type: 'rich-editor',
    icon: 'rich-editor',
    formItemFlag: true,
    options: {
      name: '',
      label: '',
      labelAlign: '',
      defaultValue: '',
      columnWidth: '200px',
      size: '',
      labelWidth: null,
      labelHidden: false,
      readonly: false,
      disabled: false,
      hidden: false,
      required: false,
      validation: '',
      validationHint: '',
      customClass: '',
      placeholder: '',
      minHeight: '200px',
      onCreated: '',
      onMounted: '',
      onChange: '',
      onValidate: '',
    },
  },
  {
    type: 'slot',
    icon: 'slot',
    category: 'field',
    options: {
      name: '',
      label: '',
      hidden: false,
      customClass: '',
      labelWidth: null,
      slotName: '',
      onCreated: '',
      onMounted: '',
    },
  },
]

export const customFields: any[] = []

export function addCustomWidgetSchema(schema: any) {
  customFields.push(schema)
}
