#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Git Hooks 安装脚本 - Auto-Dev
自动安装 pre-commit 等 Git 钩子
"""

import argparse
import os
import stat
import sys
from dataclasses import dataclass
from enum import Enum
from pathlib import Path


class HookType(Enum):
    PRE_COMMIT = "pre-commit"
    PRE_PUSH = "pre-push"
    COMMIT_MSG = "commit-msg"
    POST_COMMIT = "post-commit"


class Colors:
    RED = '\033[91m'
    YELLOW = '\033[93m'
    GREEN = '\033[92m'
    BLUE = '\033[94m'
    RESET = '\033[0m'
    BOLD = '\033[1m'
    CYAN = '\033[96m'


def color_text(text: str, color: str) -> str:
    return f"{color}{text}{Colors.RESET}"


@dataclass
class HookConfig:
    name: str
    enabled: bool = True
    checks: list = None
    block_on_fail: bool = True

    def __post_init__(self):
        if self.checks is None:
            self.checks = []


class TechDetector:
    """项目技术栈检测器（简化版，用于钩子安装）"""

    FRONTEND_FILES = ["package.json"]
    BACKEND_FILES = ["pom.xml", "build.gradle", "build.gradle.kts"]

    def __init__(self, project_root: str = "."):
        self.project_root = Path(project_root).resolve()

    def detect(self) -> str:
        """检测项目类型，返回 'frontend' 或 'backend'"""
        # 优先检测前端
        package_json = self.project_root / "package.json"
        if package_json.exists():
            try:
                import json

                with open(package_json, "r", encoding="utf-8") as f:
                    pkg = json.load(f)
                    deps = {**pkg.get("dependencies", {}), **pkg.get("devDependencies", {})}
                    pkg_names = list(deps.keys())

                    # Vue 相关
                    if any("vue" in p.lower() for p in pkg_names):
                        return "frontend"
                    # React 相关
                    if any("react" in p.lower() for p in pkg_names):
                        return "frontend"
                    # 有 package.json 但没有特定框架，可能是前端或后端 Node
                    # 检查是否有 vite.config 或明确的 Vue/React 依赖
                    if any(
                        (self.project_root / f).exists()
                        for f in ["vite.config.ts", "vite.config.js", "next.config.js"]
                    ):
                        return "frontend"
                    # 纯 Node 后端（有 express/koa/nest 但没有前端框架）
                    backend_pkgs = ["express", "koa", "nest", "fastify", "hapi"]
                    if any(pkg.lower() in deps for pkg in backend_pkgs):
                        return "backend"
                    # 默认当作前端（因为前端项目通常有更多静态资源）
                    return "frontend"
            except Exception:
                pass

        # 检测后端 Java
        if (self.project_root / "pom.xml").exists():
            return "backend"
        if (self.project_root / "build.gradle").exists() or (
            self.project_root / "build.gradle.kts"
        ).exists():
            return "backend"

        return "unknown"


class ConfigLoader:
    """加载 .auto-dev.yaml 配置文件"""

    def __init__(self, project_root: str = "."):
        self.project_root = Path(project_root)
        self.config = {}
        self._load()

    def _load(self):
        config_file = self.project_root / ".auto-dev.yaml"
        if not config_file.exists():
            print(f"Warning: {config_file} not found, using defaults")
            return

        import yaml
        with open(config_file, 'r', encoding='utf-8') as f:
            self.config = yaml.safe_load(f) or {}

    @property
    def auto_install(self) -> bool:
        hooks = self.config.get('git_hooks', {})
        return hooks.get('auto_install', True)

    @property
    def pre_commit_config(self) -> HookConfig:
        hooks = self.config.get('git_hooks', {})
        pre_commit = hooks.get('pre_commit', {})

        return HookConfig(
            name="pre-commit",
            enabled=pre_commit.get('enabled', True),
            checks=pre_commit.get('checks', ['quality_gate']),
            block_on_fail=pre_commit.get('block_on_fail', True)
        )


class HookInstaller:
    """Git钩子安装器"""

    HOOK_TEMPLATE = """#!/bin/bash
# Auto-Dev Git Hook - {hook_name}
# Generated by auto-dev at {timestamp}
# DO NOT EDIT THIS FILE MANUALLY

set -e

# 配置
PROJECT_ROOT="$(git rev-parse --show-toplevel)"
AUTO_DEV_DIR="$PROJECT_ROOT/auto-dev"
SCRIPTS_DIR="$AUTO_DEV_DIR/scripts"
BLOCK_ON_FAIL={block_on_fail}

# 颜色定义
RED='\\033[91m'
YELLOW='\\033[93m'
GREEN='\\033[92m'
BLUE='\\033[94m'
RESET='\\033[0m'
BOLD='\\033[1m'
CYAN='\\033[96m'

# 日志函数
log_info() {{
    echo -e "{{$BLUE}}[INFO]{{$RESET}} $1"
}}

log_success() {{
    echo -e "{{$GREEN}}[SUCCESS]{{$RESET}} $1"
}}

log_warning() {{
    echo -e "{{$YELLOW}}[WARNING]{{$RESET}} $1"
}}

log_error() {{
    echo -e "{{$RED}}[ERROR]{{$RESET}} $1"
}}

# 检查Python是否可用
check_python() {{
    if ! command -v python3 &> /dev/null && ! command -v python &> /dev/null; then
        log_error "Python 未安装，无法运行 auto-dev 钩子"
        exit 1
    fi
    PYTHON_CMD=$(command -v python3 || command -v python)
}}

# 执行检查
run_checks() {{
    local checks=({checks})
    local failed=0

    for check in "${{checks[@]}}"; do
        case $check in
            "quality_gate")
                log_info "执行质量门禁检查..."
                if [ -f "$SCRIPTS_DIR/quality_gate.py" ]; then
                    $PYTHON_CMD "$SCRIPTS_DIR/quality_gate.py" --project-root "$PROJECT_ROOT"
                else
                    log_warning "quality_gate.py 不存在，跳过"
                    continue
                fi
                ;;
            "security_scan")
                log_info "执行安全扫描..."
                if [ -f "$SCRIPTS_DIR/security_scan.py" ]; then
                    $PYTHON_CMD "$SCRIPTS_DIR/security_scan.py" --project-root "$PROJECT_ROOT"
                else
                    log_warning "security_scan.py 不存在，跳过"
                    continue
                fi
                ;;
            "reviewer")
                log_info "执行代码审核..."
                if [ -f "$SCRIPTS_DIR/reviewer.py" ]; then
                    $PYTHON_CMD "$SCRIPTS_DIR/reviewer.py" --project-root "$PROJECT_ROOT"
                else
                    log_warning "reviewer.py 不存在，跳过"
                    continue
                fi
                ;;
            "forbidden_check")
                log_info "执行禁止操作检查..."
                if [ -f "$SCRIPTS_DIR/quality_gate.py" ]; then
                    $PYTHON_CMD "$SCRIPTS_DIR/quality_gate.py" --project-root "$PROJECT_ROOT" --forbidden-only
                else
                    log_warning "quality_gate.py 不存在，跳过"
                    continue
                fi
                ;;
            *)
                log_warning "未知检查项: $check"
                ;;
        esac

        if [ $? -ne 0 ]; then
            failed=$((failed + 1))
            log_error "检查失败: $check"
        else
            log_success "检查通过: $check"
        fi
    done

    return $failed
}}

# 主流程
main() {{
    echo -e "{{$CYAN}}{{$BOLD}}"
    echo "========================================"
    echo "  Auto-Dev Git Hook - {hook_name}"
    echo "========================================"
    echo -e "{{$RESET}}"

    check_python

    echo ""
    log_info "开始执行 Git Hook: {hook_name}"
    echo ""

    run_checks

    local exit_code=$?

    echo ""
    if [ $exit_code -eq 0 ]; then
        log_success "所有检查通过"
        exit 0
    else
        log_error "$exit_code 个检查失败"
        if [ "$BLOCK_ON_FAIL" = true ]; then
            log_error "阻止提交，请修复上述问题后重试"
            exit 1
        else
            log_warning "允许提交 (block_on_fail=false)"
            exit 0
        fi
    fi
}}

main "$@"
"""

    def __init__(self, project_root: str = ".", force: bool = False):
        self.project_root = Path(project_root).resolve()
        self.force = force
        self.hooks_dir = self.project_root / ".git" / "hooks"
        self.auto_dev_dir = self.project_root / "auto-dev"
        self.scripts_dir = self.auto_dev_dir / "scripts"

    def install(self, hook_type: HookType = HookType.PRE_COMMIT, config: HookConfig = None) -> bool:
        """安装指定类型的钩子"""
        hook_file = self.hooks_dir / hook_type.value
        timestamp = self._get_timestamp()

        # 检查是否为Git仓库
        if not (self.project_root / ".git").exists():
            print(color_text(f"Error: {self.project_root} 不是 Git 仓库", Colors.RED))
            return False

        # 检查钩子是否已存在
        if hook_file.exists() and not self.force:
            # 检查是否已经是auto-dev钩子
            content = hook_file.read_text(encoding='utf-8', errors='ignore')
            if "Auto-Dev Git Hook" in content:
                print(color_text(f"  [SKIP] {hook_type.value} 钩子已由 auto-dev 管理", Colors.YELLOW))
                return True
            else:
                print(color_text(f"  [WARN] {hook_type.value} 钩子已存在，将被覆盖", Colors.YELLOW))
                print(color_text(f"         原始内容已备份到 {hook_type.value}.backup", Colors.YELLOW))
                backup_file = self.hooks_dir / f"{hook_type.value}.backup"
                hook_file.rename(backup_file)

        # 检查脚本目录
        if not self.scripts_dir.exists():
            print(color_text(f"Error: 脚本目录不存在: {self.scripts_dir}", Colors.RED))
            print(color_text("       请确保 auto-dev 目录存在且包含 scripts/", Colors.RED))
            return False

        # 生成钩子内容
        checks_str = " ".join(config.checks) if config and config.checks else "quality_gate"
        block_on_fail = "true" if (config and config.block_on_fail) else "false"

        hook_content = self.HOOK_TEMPLATE.format(
            hook_name=hook_type.value,
            timestamp=timestamp,
            checks=checks_str,
            block_on_fail=block_on_fail
        )

        # 写入钩子文件
        try:
            hook_file.write_text(hook_content, encoding='utf-8')

            # 设置可执行权限
            current_mode = hook_file.stat().st_mode
            hook_file.chmod(current_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

            print(color_text(f"  [OK] 已安装 {hook_type.value} 钩子", Colors.GREEN))
            return True

        except Exception as e:
            print(color_text(f"Error: 安装钩子失败: {e}", Colors.RED))
            return False

    def uninstall(self, hook_type: HookType = HookType.PRE_COMMIT) -> bool:
        """卸载指定类型的钩子"""
        hook_file = self.hooks_dir / hook_type.value

        if not hook_file.exists():
            print(color_text(f"  [SKIP] {hook_type.value} 钩子不存在", Colors.YELLOW))
            return True

        content = hook_file.read_text(encoding='utf-8', errors='ignore')
        if "Auto-Dev Git Hook" not in content:
            print(color_text(f"  [SKIP] {hook_type.value} 钩子不是由 auto-dev 管理", Colors.YELLOW))
            return False

        try:
            hook_file.unlink()
            print(color_text(f"  [OK] 已卸载 {hook_type.value} 钩子", Colors.GREEN))

            # 检查是否有备份
            backup_file = self.hooks_dir / f"{hook_type.value}.backup"
            if backup_file.exists():
                print(color_text(f"       原始钩子备份在: {hook_type.value}.backup", Colors.BLUE))

            return True

        except Exception as e:
            print(color_text(f"Error: 卸载钩子失败: {e}", Colors.RED))
            return False

    def list_hooks(self) -> list:
        """列出已安装的钩子"""
        if not self.hooks_dir.exists():
            return []

        hooks = []
        for hook_file in self.hooks_dir.iterdir():
            if hook_file.is_file() and not hook_file.name.endswith('.backup'):
                content = hook_file.read_text(encoding='utf-8', errors='ignore')
                if "Auto-Dev Git Hook" in content:
                    hooks.append({
                        'name': hook_file.name,
                        'managed': True,
                        'executable': os.access(hook_file, os.X_OK)
                    })
                else:
                    hooks.append({
                        'name': hook_file.name,
                        'managed': False,
                        'executable': os.access(hook_file, os.X_OK)
                    })

        return hooks

    def _get_timestamp(self) -> str:
        from datetime import datetime
        return datetime.now().strftime("%Y-%m-%d %H:%M:%S")


class GitHooksManager:
    """Git钩子管理器"""

    def __init__(self, project_root: str = ".", force: bool = False, project_type: str = None):
        self.installer = HookInstaller(project_root, force)
        self.config_loader = ConfigLoader(project_root)
        self.tech_detector = TechDetector(project_root)
        self.project_type = project_type or self.tech_detector.detect()

    def install_all(self) -> bool:
        """安装所有配置的钩子"""
        print(color_text("\n=== 安装 Auto-Dev Git Hooks ===", Colors.COLD + Colors.BOLD))

        # 显示检测到的项目类型
        print(color_text(f"  检测到项目类型: {self.project_type}", Colors.CYAN))

        if not self.config_loader.auto_install:
            print(color_text("  [SKIP] 自动安装已被禁用 (git_hooks.auto_install=false)", Colors.YELLOW))
            return True

        if not self.config_loader.pre_commit_config.enabled:
            print(color_text("  [SKIP] pre-commit 钩子已被禁用", Colors.YELLOW))
            return True

        pre_commit_config = self.config_loader.pre_commit_config
        success = self.installer.install(HookType.PRE_COMMIT, pre_commit_config)

        if success:
            print(color_text("\n✓ Git Hooks 安装成功!", Colors.GREEN + Colors.BOLD))
            print(color_text("  下次执行 git commit 时将自动触发检查", Colors.BLUE))
        else:
            print(color_text("\n✗ Git Hooks 安装失败", Colors.RED + Colors.BOLD))

        return success

    def uninstall_all(self) -> bool:
        """卸载所有 auto-dev 管理的钩子"""
        print(color_text("\n=== 卸载 Auto-Dev Git Hooks ===", Colors.YELLOW + Colors.BOLD))

        success = True
        for hook_type in HookType:
            if not self.installer.uninstall(hook_type):
                success = False

        return success

    def list_all(self):
        """列出所有钩子"""
        print(color_text("\n=== Git Hooks 状态 ===", Colors.CYAN + Colors.BOLD))

        hooks = self.installer.list_hooks()

        if not hooks:
            print(color_text("  暂无已安装的钩子", Colors.YELLOW))
            return

        for hook in hooks:
            managed = color_text(" [auto-dev]", Colors.GREEN) if hook['managed'] else ""
            exec_status = color_text(" ✓ executable", Colors.GREEN) if hook['executable'] else color_text(" ✗ not executable", Colors.RED)
            print(f"  {hook['name']}{managed}{exec_status}")


def main():
    parser = argparse.ArgumentParser(
        description="Auto-Dev Git Hooks 安装脚本",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
示例:
  %(prog)s install      # 安装钩子
  %(prog)s uninstall    # 卸载钩子
  %(prog)s list        # 列出已安装的钩子
  %(prog)s install -f   # 强制覆盖已存在的钩子
        """
    )
    parser.add_argument(
        'action',
        nargs='?',
        choices=['install', 'uninstall', 'list'],
        default='install',
        help='操作: install (默认), uninstall, list'
    )
    parser.add_argument(
        '--project-root', '-p',
        default='.',
        help='项目根目录 (默认: .)'
    )
    parser.add_argument(
        '--force', '-f',
        action='store_true',
        help='强制覆盖已存在的钩子'
    )
    parser.add_argument(
        '--hook',
        choices=['pre-commit', 'pre-push', 'commit-msg', 'post-commit', 'all'],
        default='all',
        help='指定要操作的钩子类型'
    )
    parser.add_argument(
        '--type',
        choices=['frontend', 'backend', 'auto'],
        default='auto',
        help='指定项目类型 (默认: auto 自动检测)'
    )
    parser.add_argument(
        '--detect-only',
        action='store_true',
        help='仅检测项目类型，不安装钩子'
    )

    args = parser.parse_args()

    manager = GitHooksManager(args.project_root, args.force, args.type if args.type != 'auto' else None)

    if args.detect_only:
        detector = TechDetector(args.project_root)
        project_type = detector.detect()
        print(f"检测到的项目类型: {project_type}")
        sys.exit(0)

    if args.action == 'install':
        if args.hook == 'all':
            success = manager.install_all()
        else:
            installer = HookInstaller(args.project_root, args.force)
            config = manager.config_loader.pre_commit_config
            success = installer.install(HookType(args.hook), config)

    elif args.action == 'uninstall':
        if args.hook == 'all':
            success = manager.uninstall_all()
        else:
            installer = HookInstaller(args.project_root, args.force)
            success = installer.uninstall(HookType(args.hook))

    elif args.action == 'list':
        manager.list_all()
        success = True

    else:
        success = False

    sys.exit(0 if success else 1)


if __name__ == '__main__':
    # 修复颜色常量拼写错误
    Colors.COLD = '\033[96m'
    main()
